Add files via upload
Gozhii/hw01 pull request #1
Opened 2019-03-24 18:04 UTC by PavelGozhii

2019-03-24 20:21 UTC, Siril-O requested changes

2019-03-24 20:21 UTC, Siril-O commented on Main.java
> +	// write your code here
Remove this commented code

2019-03-24 20:21 UTC, Siril-O commented on Matrix.java
> +    private boolean sorted = false;
false can be removed

2019-03-24 20:21 UTC, Siril-O commented on Matrix.java
> +    private Matrix existring = null;
null can be removed

2019-03-24 20:21 UTC, Siril-O commented on Matrix.java
> +        if (existring != null) {
Why do you need existring , you dont use it in calculations?

2019-03-24 20:21 UTC, Siril-O commented on Matrix.java
> +        if (existring != null) {
Remove it or explain what is the purpose to check is it is not null. Also existring  should be existing

2019-03-24 20:21 UTC, Siril-O commented on Matrix.java
> +                for(int i = 0; i < array.length; i++){System.out.print(array[i]);}
Wrong format lock should be on new line

2019-03-24 20:21 UTC, Siril-O commented on Object.java
> +public class Object {
why it is called Object ?

2019-03-24 20:21 UTC, Siril-O commented on Task1.java
> +    public int resoltOfMatch(int firstResult, int secondResult, int firtsPromise, int secondPromise){
typo in firtsPromise

2019-03-24 20:21 UTC, Siril-O commented on Task1.java
> +                        || (firstResult == secondResult && firtsPromise == secondPromise) ? 1 : 0;
you can avoid (firstResult == secondResult && firtsPromise == secondPromise) by changing previous line

2019-03-24 20:21 UTC, Siril-O commented on Task3.java
> +    public double getPow(float x, double pow){
Bad name, you are not getting Pow you are calculating it

2019-03-24 20:21 UTC, Siril-O commented on Task3.java
> +            return 1/result;
1/result   does not calculates negative power

2019-03-24 20:21 UTC, Siril-O commented on Task3.java
> +        if(pow == 0){
Is this check necessary ?

2019-03-24 20:21 UTC, Siril-O commented on Task3.java
> +        int exp = 0;
Why do you need m and exp variables ?

2019-03-24 20:21 UTC, Siril-O commented on Task4.java
> +        return  n * getFactorial(n-1);
Format spaces

2019-03-24 20:21 UTC, Siril-O commented on Task4.java
> +        if(n > 999){
Why do you perform this check ?

2019-03-24 20:21 UTC, Siril-O commented on Task5.java
> +                    arr[e] = arr[e] ^ arr[e + 1];
Create swap method and do not use ^, use some temporary variable

2019-03-24 20:21 UTC, Siril-O commented on Task5.java
> +                    arr[e] = arr[e] ^ arr[e + 1];
Remove duplicates of swap functionality in all methods

2019-03-24 20:21 UTC, Siril-O commented on Task2.java
> +        for(int i = size-2; i >= 0; i--){
why size -2 ? Will this work to print 10  stars rhombus ?

2019-03-24 20:21 UTC, Siril-O commented on Object.java
> +            outputStrm.writeObject(object);
Where it writes to and reads from ? And what task is it ?

2019-03-24 20:21 UTC, Siril-O commented on Object.java
> +            outputStrm.writeObject(object);
Please read  what should be done in 1.7  task

2019-03-24 21:38 UTC, merged

2019-03-25 13:25 UTC, PavelGozhii commented on Matrix.java
> +        if (existring != null) {
> Remove it or explain what is the purpose to check is it is not null. Also existring should be existing

нужно проверить на заполнение данными матрицы, я ведь не хочу, что бы операции были из пусто матрицей

2019-03-25 13:26 UTC, PavelGozhii commented on Task2.java
> +        for(int i = size-2; i >= 0; i--){
> why size -2 ? Will this work to print 10 stars rhombus ?

поставил 10, работает, но все равно кое что исправил